import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <main className="bg-[#2B2B2B]" >
          {children}

       
        </main>

        <footer></footer>
      </body>
    </html>
  );
}
