import avatar1 from './avatar-1.svg'
import avatar2 from './avatar-2.svg'
import avatar3 from './avatar-3.svg'
import avatar4 from './avatar-4.svg'
import avatar5 from './avatar-5.svg'
import avatar6 from './avatar-6.svg'
import avatar7 from './avatar-7.svg'
import avatar8 from './avatar-8.svg'
import avatar9 from './avatar-9.svg'
import avatar10 from './avatar-10.svg'
import avatar11 from './avatar-11.svg'
import avatar12 from './avatar-12.svg'
import samolyot from './samolyot.svg'
import icon1 from "./icon-1.svg"
import icon2 from "./icon-2.svg"
import icon3 from "./icon-3.svg"
import icon4 from "./icon-4.svg"
import icon5 from "./icon-5.svg"
import icon6 from "./icon-6.svg"
import icon7 from "./icon-7.svg"
import icon8 from "./icon-8.svg"
import smallAvatar1 from "./small-avatar1.svg"
import smallAvatar2 from "./small-avatar2.svg"
import smallAvatar3 from "./small-avatar3.svg"
import galaxy from "./galaxy.svg"
import odena from "./odena.svg"
import astronom from "./astronom.svg"
import eye from "./eye.svg"
import icon9 from "./icon9.svg"
import icon10 from "./icon10.svg"
import icon11 from "./icon11.svg"
import logo from "./logo.svg"
import socialMedia from './social-media.svg'
import kosmonavt from './kosmonavt.svg'
import bg_image from './bg-image.svg'
import hero_img from './hero-img.svg'
import hero_icon from './hero_icon.svg'
import hero_icon_samolyot from "./samolyot-icon.svg"
import dog from "./dog-img.svg"
import yumronqoziq from "./yumronqoziq-img.svg"
import cat from "./cat-img.svg"
import darner from "./darner-img.svg"
import small_darner1 from "./small-darner-1-img.svg"
import small_darner2 from "./small-darner-2-img.svg"
import robot from "./robot-img.svg"
import small_robot1 from "./small-robot-1-img.svg"
import small_robot2 from "./small-robot-2-img.svg"

export {avatar1, avatar2, avatar3, avatar4, avatar5,avatar6,avatar7,avatar8,avatar9,avatar10,avatar11,avatar12, samolyot, icon1, icon2, icon3, icon4,icon5,icon6, icon7,icon8, galaxy,odena, astronom, smallAvatar1, smallAvatar2,smallAvatar3, eye , icon9, icon11, icon10,socialMedia, logo, kosmonavt, bg_image, hero_icon, hero_icon_samolyot, hero_img, dog, small_darner2, small_darner1, darner, cat, robot, small_robot1, small_robot2, yumronqoziq}